apiVersion: batch/v1
kind: Job
metadata:
  name: cowsay-pre-install
  namespace: default
  labels:
    app: cowsay
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      restartPolicy: Never
      containers:
      - name: cowsay
        image: docker/whalesay
        command: ["/bin/sh", "-c", "env"]
