apiVersion: batch/v1
kind: Job
metadata:
  name: cowsay-pre-install
  namespace: default
  labels:
    app: cowsay
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      restartPolicy: Never
      containers:
      - name: cowsay
        image: docker/whalesay
        command: ["/bin/sh -c 'env'"]
